"""Add assigned_event_id to User

Revision ID: 9a30884c2400
Revises: f27443f528aa
Create Date: 2026-04-04 18:43:14.185467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a30884c2400'
down_revision: Union[str, None] = 'f27443f528aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('assigned_event_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'events', ['assigned_event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'assigned_event_id')
    # ### end Alembic commands ###
